openapi: 3.0.0
info:
  title: API Backend RIWI
  version: 1.0.0
  description: Documentación de la API
servers:
  - url: http://localhost:3000/api
paths:
  /users:
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Usuarios
      responses:
        200:
          description: Lista de usuarios